### ISSUE TITLE
message div does not display in example

### ISSUE THREAD

**Issue by curriouscat** [webismymind/editablegrid-mysql-example#20]
Wonderful software. Thank you. 
I notice that the message line does not display in this mysql-example. It does in the 'full example' in the full master. I found that I could not work out how to activate or have the message to display. It could be useful.

**Comment by shortfuze** [comment]
not sure where your code is
I added a message to my index.html  and it showed up .

```
<!-- Feedback message zone -->
			<div id="message">message goes here</div>
```

but with all the editing i've done in the past , I don't know if it didn't work before or not.
