### ISSUE TITLE
Regarding CellEditor

### ISSUE THREAD

**Issue by vivekiist** [webismymind/editablegrid-mysql-example#27]
Hi, 
Thanks for the awesome example. I have a few questions?
1. I have a long text in one of the columns. When i click to edit the text, it appears as one single line. Is it possible to wrap text while editing also?
2. How can insert new line character in the long text? (i.e. I want the text to appear as bullets or numbered list)
3. How can I enable charts? I really have no idea :(

**Comment by jybeaujean** [comment]
You should use a renderer and and editor for your column.
[description_editor.js.txt](https://github.com/webismymind/editablegrid-mysql-example/files/270306/description_editor.js.txt)
