### ISSUE TITLE
edit dates

### ISSUE THREAD

**Issue by alex-est** [webismymind/editablegrid-mysql-example#30]
Hello! Use your software for my purposes, very helpful. How do I set up the ability to edit dates? I use your configuration and settings (just use other names of the columns).

**Comment by jybeaujean** [comment]
The format is very important : 
load : $result = $mysqli->query('SELECT *, **date_format(lastvisit, "%d/%m/%Y") as lastvisit** FROM '.$mydb_tablename );

update : 

// Here, this is a little tips to manage date format before update the table
if ($coltype == 'date') {
   if ($value === "") 
  	 $value = NULL;
   else {
      $date_info = date_parse_from_format('d/m/Y', $value);
      $value = "{$date_info['year']}-{$date_info['month']}-{$date_info['day']}";
   }
}
