### ISSUE TITLE
I have table with 4 foreign keys

### ISSUE THREAD

**Issue by coolguys5253** [webismymind/editablegrid-mysql-example#32]
I am a new developer and i am not getting where to start using this, can you help where to start PHP Mysql Editable Grid

**Comment by jybeaujean** [comment]
What's exactly your problem ? Perhaps you should read : https://github.com/webismymind/editablegrid-mysql-example/blob/master/README.md. This is a really simple example that browses main features when you want use EditableGrid with MySQL
