### ISSUE TITLE
Not fetching 1000 records in Select Dropdown? and showing Blank Page

### ISSUE THREAD

**Issue by coolguys5253** [webismymind/editablegrid-mysql-example#33]
We want to fetch 1000 Customer Names in Select Dropdown Like this But Whole Page is blank???

$grid->addColumn('Customer_No', 'Customer', 'string', fetch_pairs($mysqli,'SELECT No, Name FROM customers'),true ); in loaddata.php

**Comment by jybeaujean** [comment]
Any error in the browser's console or in the webserver's error log file ?

**Comment by coolguys5253** [comment]
Please check these screenshots

Browser Screenshot with Error :- http://prntscr.com/b32k2s
Code Screenshot :- http://prntscr.com/b32kir

(Working Fine)Browser Screenshot after commenting out that 1000s customer record line :- http://prntscr.com/b32lfg
Code Screenshot :- http://prntscr.com/b32llg

Using 'limit 900' its working http://prntscr.com/b32omk
Using 'limit 1000' its not working http://prntscr.com/b32p2z

Can we not use something like this?

$grid->addColumn('Customer_No', 'Customer', 'string', fetch_pairs($mysqli,'SELECT No, Name FROM customers where Name=??'),true );

Thankful to you in advance :)

**Comment by jybeaujean** [comment]
Sol : Char encoding problem.

**Comment by TatsuSheva** [comment]
Did you find an answer ?
