### ISSUE TITLE
Delete action not working

### ISSUE THREAD

**Issue by GammaScorpii** [webismymind/editablegrid-mysql-example#45]
I have made my own database and table with everything working except for the delete function. When I click the trash icon my alert says:
Are you sure you want to delete the row id null

My table has a column called id and it is unique and auto increment. Since it's reading null I assume something isn't working properly? How to I track down the problem?

This is my delete.php but I am quite sure I did not change this.

`<?php

require_once('config.php');         

// Database connection                                   
$mysqli = mysqli_init();
$mysqli->options(MYSQLI_OPT_CONNECT_TIMEOUT, 5);
$mysqli->real_connect($config['db_host'],$config['db_user'],$config['db_password'],$config['db_name']); 

// Get all parameter provided by the javascript
$id = $mysqli->real_escape_string(strip_tags($_POST['id']));
$tablename = $mysqli->real_escape_string(strip_tags($_POST['tablename']));

// This very generic. So this script can be used to update several tables.
$return=false;
if ( $stmt = $mysqli->prepare("DELETE FROM ".$tablename."  WHERE id = ?")) {
	$stmt->bind_param("i", $id);
	$return = $stmt->execute();
	$stmt->close();
}             
$mysqli->close();        

echo $return ? "ok" : "error";
`

**Comment by TxEdgeMan** [comment]
Make sure that you update 'id' to your record_id field name in SQL DB in both delete.php:
if ( $stmt = $mysqli->prepare("DELETE FROM ".$tablename." WHERE **id** = ?")) {

and in loaddata.php:
$grid->addColumn('action', 'Action', 'html', NULL, false, '**id**');

**Comment by GammaScorpii** [comment]
Thank you! I had forgotten to update the name of that loaddata.php id field name.
